version: 0.2

phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn clean install
  post_build:
    commands:
    - echo "Entered the post-build phase"
artifacts:
  base-directory: 'target/'
  discard-paths: yes
  files:
    - '**/user-portal-0.0.1-SNAPSHOT.jar'
  name: hackathon-2019a-prod