version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package
artifacts:
  type: none
  files:
    - 'target/user-portal-0.0.1-SNAPSHOT.jar'
